// <auto-generated />
using System;
using LaoHR.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaoHR.API.Migrations
{
    [DbContext(typeof(LaoHRDbContext))]
    [Migration("20260114020905_AddCompanyStructure")]
    partial class AddCompanyStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaoHR.Shared.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ClockInLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("ClockInLongitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("ClockInMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ClockOutLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("ClockOutLongitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("ClockOutMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEarlyLeave")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("WorkHours")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.CompanySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyNameLao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LSSOCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("TaxRisId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VillageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("VillageId");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartmentNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(2318),
                            DepartmentCode = "ADMIN",
                            DepartmentName = "ບໍລິຫານ",
                            DepartmentNameEn = "Administration",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(2862),
                            DepartmentCode = "FIN",
                            DepartmentName = "ການເງິນ",
                            DepartmentNameEn = "Finance & Accounting",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(2864),
                            DepartmentCode = "IT",
                            DepartmentName = "ເຕັກນິກ",
                            DepartmentNameEn = "Information Technology",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(2865),
                            DepartmentCode = "SALES",
                            DepartmentName = "ການຂາຍ",
                            DepartmentNameEn = "Sales & Marketing",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.District", b =>
                {
                    b.Property<int>("DiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiId"));

                    b.Property<string>("DiName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrId")
                        .HasColumnType("int");

                    b.HasKey("DiId");

                    b.HasIndex("PrId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DependentCount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LaoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NssfId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalaryCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BaseSalary = 8000000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(4580),
                            DepartmentId = 3,
                            DependentCount = 0,
                            Email = "somphon@laohr.la",
                            EmployeeCode = "EMP001",
                            EnglishName = "Somphon Khamsouk",
                            Gender = "Male",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Software Engineer",
                            LaoName = "ສົມພອນ ຄຳສຸກ",
                            Phone = "020 5555 1234",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 2,
                            BaseSalary = 12000000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(6293),
                            DepartmentId = 1,
                            DependentCount = 0,
                            Email = "davanh@laohr.la",
                            EmployeeCode = "EMP002",
                            EnglishName = "Davanh Sisavath",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "HR Manager",
                            LaoName = "ດາວັນ ສີສະຫວັດ",
                            Phone = "020 5555 5678",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 3,
                            BaseSalary = 9500000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(6300),
                            DepartmentId = 2,
                            DependentCount = 0,
                            Email = "manivanh@laohr.la",
                            EmployeeCode = "EMP003",
                            EnglishName = "Manivanh Souksavan",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Accountant",
                            LaoName = "ມະນີວັນ ສຸກສະຫວັນ",
                            Phone = "020 5555 9012",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 4,
                            BaseSalary = 11000000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(6303),
                            DepartmentId = 4,
                            DependentCount = 0,
                            Email = "phouvong@laohr.la",
                            EmployeeCode = "EMP004",
                            EnglishName = "Phouvong Xaiyavong",
                            Gender = "Male",
                            HireDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Sales Manager",
                            LaoName = "ພູວົງ ໄຊຍະວົງ",
                            Phone = "020 5555 3456",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 5,
                            BaseSalary = 7500000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(6305),
                            DepartmentId = 4,
                            DependentCount = 0,
                            Email = "bounmi@laohr.la",
                            EmployeeCode = "EMP005",
                            EnglishName = "Bounmi Vongphachan",
                            Gender = "Male",
                            HireDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobTitle = "Marketing Specialist",
                            LaoName = "ບຸນມີ ວົງພະຈັນ",
                            Phone = "020 5555 7890",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 6,
                            BaseSalary = 6500000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(6308),
                            DepartmentId = 1,
                            DependentCount = 0,
                            Email = "souphaphon@laohr.la",
                            EmployeeCode = "EMP006",
                            EnglishName = "Souphaphon Nang",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Office Administrator",
                            LaoName = "ນາງ ສຸພາພອນ",
                            Phone = "020 5555 2468",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 7,
                            BaseSalary = 15000000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(6310),
                            DepartmentId = 3,
                            DependentCount = 0,
                            Email = "vilayphon@laohr.la",
                            EmployeeCode = "EMP007",
                            EnglishName = "Vilayphon Keomanee",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Senior Developer",
                            LaoName = "ວິໄລພອນ ແກ້ວມະນີ",
                            Phone = "020 5555 1357",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 8,
                            BaseSalary = 25000000m,
                            CreatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(6313),
                            DepartmentId = 2,
                            DependentCount = 0,
                            Email = "chanthala@laohr.la",
                            EmployeeCode = "EMP008",
                            EnglishName = "Chanthala Phommavong",
                            Gender = "Female",
                            HireDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "CFO",
                            LaoName = "ຈັນທະລາ ພົມມະວົງ",
                            Phone = "020 5555 8642",
                            SalaryCurrency = "LAK"
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.EmployeeDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("HolidayId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            HolidayId = 1,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Name = "ປີໃໝ່ສາກົນ",
                            NameEn = "International New Year",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 2,
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Name = "ວັນແມ່ຍິງສາກົນ",
                            NameEn = "International Women's Day",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 3,
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = false,
                            Name = "ວັນປີໃໝ່ລາວ",
                            NameEn = "Lao New Year (Day 1)",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 4,
                            Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = false,
                            Name = "ວັນປີໃໝ່ລາວ",
                            NameEn = "Lao New Year (Day 2)",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 5,
                            Date = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = false,
                            Name = "ວັນປີໃໝ່ລາວ",
                            NameEn = "Lao New Year (Day 3)",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 6,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Name = "ວັນກຳມະກອນສາກົນ",
                            NameEn = "International Labour Day",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 7,
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Name = "ວັນເດັກນ້ອຍສາກົນ",
                            NameEn = "International Children's Day",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 8,
                            Date = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Name = "ວັນແມ່ຍິງລາວ",
                            NameEn = "Lao Women's Union Day",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 9,
                            Date = new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Name = "ວັນຄູແຫ່ງຊາດ",
                            NameEn = "National Teacher's Day",
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 10,
                            Date = new DateTime(2026, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Name = "ວັນຊາດ",
                            NameEn = "National Day",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("ApproverNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.HasKey("LeaveId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.PayrollPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PeriodId");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("PayrollPeriods");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Province", b =>
                {
                    b.Property<int>("PrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrId"));

                    b.Property<string>("PrName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PrId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.SalarySlip", b =>
                {
                    b.Property<int>("SlipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlipId"));

                    b.Property<decimal>("Allowances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfEmployeeDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfEmployerContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TaxDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableIncome")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SlipId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PeriodId");

                    b.ToTable("SalarySlips");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingKey = "NSSF_CEILING_BASE",
                            Description = "Maximum salary for NSSF calculation",
                            SettingValue = "4500000",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1243)
                        },
                        new
                        {
                            SettingKey = "NSSF_EMPLOYEE_RATE",
                            Description = "Employee NSSF contribution rate (5.5%)",
                            SettingValue = "0.055",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1734)
                        },
                        new
                        {
                            SettingKey = "NSSF_EMPLOYER_RATE",
                            Description = "Employer NSSF contribution rate (6.0%)",
                            SettingValue = "0.060",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1736)
                        },
                        new
                        {
                            SettingKey = "WORK_START_TIME",
                            Description = "Standard work start time",
                            SettingValue = "08:30",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1737)
                        },
                        new
                        {
                            SettingKey = "WORK_END_TIME",
                            Description = "Standard work end time",
                            SettingValue = "17:30",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1737)
                        },
                        new
                        {
                            SettingKey = "EX_RATE_USD",
                            Description = "USD to LAK Exchange Rate",
                            SettingValue = "22000",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1738)
                        },
                        new
                        {
                            SettingKey = "EX_RATE_THB",
                            Description = "THB to LAK Exchange Rate",
                            SettingValue = "650",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1739)
                        },
                        new
                        {
                            SettingKey = "ZKTECO_ENABLED",
                            Description = "Global Switch for ZKTeco Integration",
                            SettingValue = "false",
                            UpdatedAt = new DateTime(2026, 1, 14, 2, 9, 4, 592, DateTimeKind.Utc).AddTicks(1739)
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.TaxBracket", b =>
                {
                    b.Property<int>("BracketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BracketId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("BracketId");

                    b.ToTable("TaxBrackets");

                    b.HasData(
                        new
                        {
                            BracketId = 1,
                            IsActive = true,
                            MaxIncome = 1300000m,
                            MinIncome = 0m,
                            SortOrder = 1,
                            TaxRate = 0.00m
                        },
                        new
                        {
                            BracketId = 2,
                            IsActive = true,
                            MaxIncome = 5000000m,
                            MinIncome = 1300001m,
                            SortOrder = 2,
                            TaxRate = 0.05m
                        },
                        new
                        {
                            BracketId = 3,
                            IsActive = true,
                            MaxIncome = 15000000m,
                            MinIncome = 5000001m,
                            SortOrder = 3,
                            TaxRate = 0.10m
                        },
                        new
                        {
                            BracketId = 4,
                            IsActive = true,
                            MaxIncome = 25000000m,
                            MinIncome = 15000001m,
                            SortOrder = 4,
                            TaxRate = 0.15m
                        },
                        new
                        {
                            BracketId = 5,
                            IsActive = true,
                            MaxIncome = 65000000m,
                            MinIncome = 25000001m,
                            SortOrder = 5,
                            TaxRate = 0.20m
                        },
                        new
                        {
                            BracketId = 6,
                            IsActive = true,
                            MaxIncome = 9999999999999999m,
                            MinIncome = 65000001m,
                            SortOrder = 6,
                            TaxRate = 0.25m
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Village", b =>
                {
                    b.Property<int>("VillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VillId"));

                    b.Property<int>("DiId")
                        .HasColumnType("int");

                    b.Property<string>("VillName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VillNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("VillId");

                    b.HasIndex("DiId");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Attendance", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.CompanySetting", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("LaoHR.Shared.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.HasOne("LaoHR.Shared.Models.Village", "Village")
                        .WithMany()
                        .HasForeignKey("VillageId");

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.District", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Employee", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.EmployeeDocument", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.LeaveRequest", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.SalarySlip", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany("SalarySlips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaoHR.Shared.Models.PayrollPeriod", "PayrollPeriod")
                        .WithMany("SalarySlips")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Village", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.District", "District")
                        .WithMany("Villages")
                        .HasForeignKey("DiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.District", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("LeaveRequests");

                    b.Navigation("SalarySlips");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.PayrollPeriod", b =>
                {
                    b.Navigation("SalarySlips");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
