// <auto-generated />
using System;
using LaoHR.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaoHR.API.Migrations
{
    [DbContext(typeof(LaoHRDbContext))]
    [Migration("20260116072437_AddBonusToSalarySlip")]
    partial class AddBonusToSalarySlip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaoHR.Shared.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ClockInLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("ClockInLongitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("ClockInMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ClockOutLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("ClockOutLongitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("ClockOutMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEarlyLeave")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("WorkHours")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.CompanySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyNameLao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LSSOCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("TaxRisId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VillageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("VillageId");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.ConversionRate", b =>
                {
                    b.Property<int>("ConversionRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversionRateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversionRateId");

                    b.ToTable("ConversionRates");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartmentNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(8586),
                            DepartmentCode = "ADMIN",
                            DepartmentName = "ບໍລິຫານ",
                            DepartmentNameEn = "Administration",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(9397),
                            DepartmentCode = "FIN",
                            DepartmentName = "ການເງິນ",
                            DepartmentNameEn = "Finance & Accounting",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(9400),
                            DepartmentCode = "IT",
                            DepartmentName = "ເຕັກນິກ",
                            DepartmentNameEn = "Information Technology",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(9402),
                            DepartmentCode = "SALES",
                            DepartmentName = "ການຂາຍ",
                            DepartmentNameEn = "Sales & Marketing",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.District", b =>
                {
                    b.Property<int>("DiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiId"));

                    b.Property<string>("DiName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrId")
                        .HasColumnType("int");

                    b.HasKey("DiId");

                    b.HasIndex("PrId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DependentCount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LaoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NssfId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalaryCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BaseSalary = 8000000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(2021),
                            DepartmentId = 3,
                            DependentCount = 0,
                            Email = "somphon@laohr.la",
                            EmployeeCode = "EMP001",
                            EnglishName = "Somphon Khamsouk",
                            Gender = "Male",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Software Engineer",
                            LaoName = "ສົມພອນ ຄຳສຸກ",
                            Phone = "020 5555 1234",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 2,
                            BaseSalary = 12000000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(5082),
                            DepartmentId = 1,
                            DependentCount = 0,
                            Email = "davanh@laohr.la",
                            EmployeeCode = "EMP002",
                            EnglishName = "Davanh Sisavath",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "HR Manager",
                            LaoName = "ດາວັນ ສີສະຫວັດ",
                            Phone = "020 5555 5678",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 3,
                            BaseSalary = 9500000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(5090),
                            DepartmentId = 2,
                            DependentCount = 0,
                            Email = "manivanh@laohr.la",
                            EmployeeCode = "EMP003",
                            EnglishName = "Manivanh Souksavan",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Accountant",
                            LaoName = "ມະນີວັນ ສຸກສະຫວັນ",
                            Phone = "020 5555 9012",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 4,
                            BaseSalary = 11000000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(5095),
                            DepartmentId = 4,
                            DependentCount = 0,
                            Email = "phouvong@laohr.la",
                            EmployeeCode = "EMP004",
                            EnglishName = "Phouvong Xaiyavong",
                            Gender = "Male",
                            HireDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Sales Manager",
                            LaoName = "ພູວົງ ໄຊຍະວົງ",
                            Phone = "020 5555 3456",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 5,
                            BaseSalary = 7500000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(5099),
                            DepartmentId = 4,
                            DependentCount = 0,
                            Email = "bounmi@laohr.la",
                            EmployeeCode = "EMP005",
                            EnglishName = "Bounmi Vongphachan",
                            Gender = "Male",
                            HireDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobTitle = "Marketing Specialist",
                            LaoName = "ບຸນມີ ວົງພະຈັນ",
                            Phone = "020 5555 7890",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 6,
                            BaseSalary = 6500000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(5102),
                            DepartmentId = 1,
                            DependentCount = 0,
                            Email = "souphaphon@laohr.la",
                            EmployeeCode = "EMP006",
                            EnglishName = "Souphaphon Nang",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Office Administrator",
                            LaoName = "ນາງ ສຸພາພອນ",
                            Phone = "020 5555 2468",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 7,
                            BaseSalary = 15000000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(5106),
                            DepartmentId = 3,
                            DependentCount = 0,
                            Email = "vilayphon@laohr.la",
                            EmployeeCode = "EMP007",
                            EnglishName = "Vilayphon Keomanee",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Senior Developer",
                            LaoName = "ວິໄລພອນ ແກ້ວມະນີ",
                            Phone = "020 5555 1357",
                            SalaryCurrency = "LAK"
                        },
                        new
                        {
                            EmployeeId = 8,
                            BaseSalary = 25000000m,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(5110),
                            DepartmentId = 2,
                            DependentCount = 0,
                            Email = "chanthala@laohr.la",
                            EmployeeCode = "EMP008",
                            EnglishName = "Chanthala Phommavong",
                            Gender = "Female",
                            HireDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "CFO",
                            LaoName = "ຈັນທະລາ ພົມມະວົງ",
                            Phone = "020 5555 8642",
                            SalaryCurrency = "LAK"
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.EmployeeDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameLao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("HolidayId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            HolidayId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(9931),
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = true,
                            Name = "International New Year",
                            NameLao = "ປີໃໝ່ສາກົນ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(9931),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 2,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1042),
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = true,
                            Name = "International Women's Day",
                            NameLao = "ວັນແມ່ຍິງສາກົນ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1042),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 3,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1046),
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = false,
                            Name = "Lao New Year (Day 1)",
                            NameLao = "ວັນປີໃໝ່ລາວ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1046),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 4,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1070),
                            Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = false,
                            Name = "Lao New Year (Day 2)",
                            NameLao = "ວັນປີໃໝ່ລາວ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1070),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 5,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1072),
                            Date = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = false,
                            Name = "Lao New Year (Day 3)",
                            NameLao = "ວັນປີໃໝ່ລາວ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1072),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 6,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1074),
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = true,
                            Name = "International Labour Day",
                            NameLao = "ວັນກຳມະກອນສາກົນ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1074),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 7,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1076),
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = true,
                            Name = "International Children's Day",
                            NameLao = "ວັນເດັກນ້ອຍສາກົນ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1077),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 8,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1078),
                            Date = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = true,
                            Name = "Lao Women's Union Day",
                            NameLao = "ວັນແມ່ຍິງລາວ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1079),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 9,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1080),
                            Date = new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = true,
                            Name = "National Teacher's Day",
                            NameLao = "ວັນຄູແຫ່ງຊາດ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1081),
                            Year = 2026
                        },
                        new
                        {
                            HolidayId = 10,
                            CreatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1082),
                            Date = new DateTime(2026, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRecurring = true,
                            Name = "National Day",
                            NameLao = "ວັນຊາດ",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 154, DateTimeKind.Utc).AddTicks(1083),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.LeaveBalance", b =>
                {
                    b.Property<int>("LeaveBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveBalanceId"));

                    b.Property<decimal>("CarriedOverDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("LeaveBalanceId");

                    b.HasIndex("EmployeeId", "LeaveType", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.LeavePolicy", b =>
                {
                    b.Property<int>("LeavePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeavePolicyId"));

                    b.Property<decimal>("AccrualPerMonth")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("AllowHalfDay")
                        .HasColumnType("bit");

                    b.Property<int>("AnnualQuota")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LeaveTypeLao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxCarryOver")
                        .HasColumnType("int");

                    b.Property<int>("MinDaysForAttachment")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAttachment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeavePolicyId");

                    b.HasIndex("LeaveType")
                        .IsUnique();

                    b.ToTable("LeavePolicies");

                    b.HasData(
                        new
                        {
                            LeavePolicyId = 1,
                            AccrualPerMonth = 1.25m,
                            AllowHalfDay = true,
                            AnnualQuota = 15,
                            IsActive = true,
                            LeaveType = "ANNUAL",
                            LeaveTypeLao = "ພັກປະຈຳປີ",
                            MaxCarryOver = 5,
                            MinDaysForAttachment = 0,
                            RequiresAttachment = false,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 152, DateTimeKind.Utc).AddTicks(6192)
                        },
                        new
                        {
                            LeavePolicyId = 2,
                            AccrualPerMonth = 0m,
                            AllowHalfDay = true,
                            AnnualQuota = 30,
                            IsActive = true,
                            LeaveType = "SICK",
                            LeaveTypeLao = "ພັກປ່ວຍ",
                            MaxCarryOver = 0,
                            MinDaysForAttachment = 3,
                            RequiresAttachment = true,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 152, DateTimeKind.Utc).AddTicks(8124)
                        },
                        new
                        {
                            LeavePolicyId = 3,
                            AccrualPerMonth = 0m,
                            AllowHalfDay = true,
                            AnnualQuota = 3,
                            IsActive = true,
                            LeaveType = "PERSONAL",
                            LeaveTypeLao = "ພັກສ່ວນຕົວ",
                            MaxCarryOver = 0,
                            MinDaysForAttachment = 0,
                            RequiresAttachment = false,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 152, DateTimeKind.Utc).AddTicks(8442)
                        },
                        new
                        {
                            LeavePolicyId = 4,
                            AccrualPerMonth = 0m,
                            AllowHalfDay = false,
                            AnnualQuota = 90,
                            IsActive = true,
                            LeaveType = "MATERNITY",
                            LeaveTypeLao = "ພັກເກີດລູກ",
                            MaxCarryOver = 0,
                            MinDaysForAttachment = 0,
                            RequiresAttachment = false,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 152, DateTimeKind.Utc).AddTicks(8444)
                        },
                        new
                        {
                            LeavePolicyId = 5,
                            AccrualPerMonth = 0m,
                            AllowHalfDay = false,
                            AnnualQuota = 15,
                            IsActive = true,
                            LeaveType = "PATERNITY",
                            LeaveTypeLao = "ພັກພໍ່ເກີດລູກ",
                            MaxCarryOver = 0,
                            MinDaysForAttachment = 0,
                            RequiresAttachment = false,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 152, DateTimeKind.Utc).AddTicks(8447)
                        },
                        new
                        {
                            LeavePolicyId = 6,
                            AccrualPerMonth = 0m,
                            AllowHalfDay = false,
                            AnnualQuota = 365,
                            IsActive = true,
                            LeaveType = "UNPAID",
                            LeaveTypeLao = "ພັກບໍ່ໄດ້ເງິນ",
                            MaxCarryOver = 0,
                            MinDaysForAttachment = 0,
                            RequiresAttachment = false,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 152, DateTimeKind.Utc).AddTicks(8448)
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("ApproverNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HalfDayType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("LeaveId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.PayrollPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PeriodId");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("PayrollPeriods");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Province", b =>
                {
                    b.Property<int>("PrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrId"));

                    b.Property<string>("PrName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PrId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.SalarySlip", b =>
                {
                    b.Property<int>("SlipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlipId"));

                    b.Property<decimal>("Allowances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSalaryOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GrossIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSalaryOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfEmployeeDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfEmployerContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TaxDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableIncome")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SlipId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PeriodId");

                    b.ToTable("SalarySlips");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingKey = "NSSF_CEILING_BASE",
                            Description = "Maximum salary for NSSF calculation",
                            SettingValue = "4500000",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7104)
                        },
                        new
                        {
                            SettingKey = "NSSF_EMPLOYEE_RATE",
                            Description = "Employee NSSF contribution rate (5.5%)",
                            SettingValue = "0.055",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7683)
                        },
                        new
                        {
                            SettingKey = "NSSF_EMPLOYER_RATE",
                            Description = "Employer NSSF contribution rate (6.0%)",
                            SettingValue = "0.060",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7686)
                        },
                        new
                        {
                            SettingKey = "WORK_START_TIME",
                            Description = "Standard work start time",
                            SettingValue = "08:30",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7687)
                        },
                        new
                        {
                            SettingKey = "WORK_END_TIME",
                            Description = "Standard work end time",
                            SettingValue = "17:30",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7688)
                        },
                        new
                        {
                            SettingKey = "EX_RATE_USD",
                            Description = "USD to LAK Exchange Rate",
                            SettingValue = "22000",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7689)
                        },
                        new
                        {
                            SettingKey = "EX_RATE_THB",
                            Description = "THB to LAK Exchange Rate",
                            SettingValue = "650",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7691)
                        },
                        new
                        {
                            SettingKey = "ZKTECO_ENABLED",
                            Description = "Global Switch for ZKTeco Integration",
                            SettingValue = "false",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 24, 36, 153, DateTimeKind.Utc).AddTicks(7692)
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.TaxBracket", b =>
                {
                    b.Property<int>("BracketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BracketId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("BracketId");

                    b.ToTable("TaxBrackets");

                    b.HasData(
                        new
                        {
                            BracketId = 1,
                            IsActive = true,
                            MaxIncome = 1300000m,
                            MinIncome = 0m,
                            SortOrder = 1,
                            TaxRate = 0.00m
                        },
                        new
                        {
                            BracketId = 2,
                            IsActive = true,
                            MaxIncome = 5000000m,
                            MinIncome = 1300001m,
                            SortOrder = 2,
                            TaxRate = 0.05m
                        },
                        new
                        {
                            BracketId = 3,
                            IsActive = true,
                            MaxIncome = 15000000m,
                            MinIncome = 5000001m,
                            SortOrder = 3,
                            TaxRate = 0.10m
                        },
                        new
                        {
                            BracketId = 4,
                            IsActive = true,
                            MaxIncome = 25000000m,
                            MinIncome = 15000001m,
                            SortOrder = 4,
                            TaxRate = 0.15m
                        },
                        new
                        {
                            BracketId = 5,
                            IsActive = true,
                            MaxIncome = 65000000m,
                            MinIncome = 25000001m,
                            SortOrder = 5,
                            TaxRate = 0.20m
                        },
                        new
                        {
                            BracketId = 6,
                            IsActive = true,
                            MaxIncome = 9999999999999999m,
                            MinIncome = 65000001m,
                            SortOrder = 6,
                            TaxRate = 0.25m
                        });
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Village", b =>
                {
                    b.Property<int>("VillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VillId"));

                    b.Property<int>("DiId")
                        .HasColumnType("int");

                    b.Property<string>("VillName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VillNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("VillId");

                    b.HasIndex("DiId");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.WorkSchedule", b =>
                {
                    b.Property<int>("WorkScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkScheduleId"));

                    b.Property<TimeSpan>("BreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BreakStartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("DailyWorkHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<int>("LateThresholdMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("SaturdayEndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("SaturdayHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan?>("SaturdayStartTime")
                        .HasColumnType("time");

                    b.Property<string>("SaturdayWeeks")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SaturdayWorkType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("StandardMonthlyHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("WorkEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkStartTime")
                        .HasColumnType("time");

                    b.HasKey("WorkScheduleId");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Attendance", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.CompanySetting", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("LaoHR.Shared.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.HasOne("LaoHR.Shared.Models.Village", "Village")
                        .WithMany()
                        .HasForeignKey("VillageId");

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.District", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Employee", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.EmployeeDocument", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.LeaveBalance", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.LeaveRequest", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.SalarySlip", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.Employee", "Employee")
                        .WithMany("SalarySlips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaoHR.Shared.Models.PayrollPeriod", "PayrollPeriod")
                        .WithMany("SalarySlips")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Village", b =>
                {
                    b.HasOne("LaoHR.Shared.Models.District", "District")
                        .WithMany("Villages")
                        .HasForeignKey("DiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.District", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("LeaveRequests");

                    b.Navigation("SalarySlips");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.PayrollPeriod", b =>
                {
                    b.Navigation("SalarySlips");
                });

            modelBuilder.Entity("LaoHR.Shared.Models.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
